config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "hotels#index"
  get "/pages/:page" => "pages#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_attached_file :image, styles: {
    medium: "320x210>"
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:title, :description, :note, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(hotel, multipart: true) do |f| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<section id="add">
    <div class="add__box">
      <form action="#">
        <%= f.text_field :title, placeholder: "Titre", required: true %>
        <%= f.text_area :description, placeholder: "Description", required: true %>
        <div class="add__box-end">
          <div class="add__box-rating">
            <h3>Note</h3>
            <fieldset class="rating">
              <%= f.hidden_field :note, min: 1, max: 5 %>
              <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="5"></label>
              <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="4"></label>
              <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="3"></label>
              <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="2"></label>
              <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="1"></label>
            </fieldset>
          </div>
          <%= f.file_field :image, required: true %>
          <input type="submit" value="Submit">
        </div>
      </form>
    </div>
  </section>


  <% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
  <header>
    <form accept-charset="UTF-8" method="get">
      <a href="/"><%= image_tag image_path('icons/logo.svg'), alt: :logo %></a>
    </form>
    <div>
      <a href="add.html"><%= link_to 'New Hotel', new_hotel_path %></a>
      <a href="pages/about">A propos</a>
    </div>
  </header>
  <section id="list">
    <% @hotels.each do |hotel| %>
      <div class="element">
        <div class="element__left">
          <%= image_tag hotel.image.url(:medium), class: 'element__left-img' %>
        </div>
        <div class="element__right">
          <h3><%= hotel.title %></h3>
          <span class="element__right-stars">
            <% case hotel.note %>
            <% when 1 %>
                <%= image_tag image_path('icons/star-f.svg') %>
            <% when 2 %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
            <% when 3 %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
            <% when 4 %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
            <% when 5 %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
                <%= image_tag image_path('icons/star-f.svg') %>
           <% end %>
          </span>

          <!-- <h4>par <a href="#">Utilisateur</a></h4> -->
          <p><td><%= hotel.description %></td></p>
        </div>
      </div>
    <% end %>
  </section>

app/views/hotels/new.html.erb
<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path, class: "return" %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hotel.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>Note:</strong>
  <%= @hotel.note %>
</p>

<p>
  <strong>IMAGE : </strong>
  <%= image_tag @hotel.image.url(:medium) %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path, class: "return" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Braw</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/about.html.erb
<header>
  <form accept-charset="UTF-8" method="get">
    <a href="../../"><%= image_tag image_path('icons/logo.svg'), alt: :logo %></a>
  </form>
  <div>
    <a href="add.html"><%= link_to 'New Hotel', new_hotel_path %></a>
    <a href="#">A propos</a>
  </div>
</header>
<section class="about">
  <h1>About</h1>
  <p>This app has been created to learn Ruby on Rails @ IUT Bordeaux Montaigne.</p>
  <p>It has been developped w/ <%= image_tag image_path('icons/heart.svg'), alt: :logo %> by <a href="//bastienrobert.fr" target="_blank">Bastien Robert</a>.</p>
</section>